// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/build": {
    params: {};
  };
  "/play": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/build" | "/play";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/build.tsx": {
    id: "routes/build";
    page: "/build";
  };
  "routes/play.tsx": {
    id: "routes/play";
    page: "/play";
  };
};